Gesture_Go_v1/Controllers/AdmImagensController.cs
using System;
using System.Web.Security;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gesture_Go_v1.Models;
using System.IO;

namespace Gesture_Go_v1.Controllers
{
    public class AdmImagensController : Controller
    {
        private Contexto db = new Contexto();

        [Authorize (Roles = "1")]
        public ActionResult AddImagens()
        {
            var lista = db.Imagem.ToList();
            return View("ExibirImagens", lista);
        }

        [Authorize(Roles = "1")]
        public ActionResult ExibirImagens()
        {
            var lista = db.Imagem.ToList();
            return View(lista);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public JsonResult Delete(int id)
        {
            if(id == null)
            {
                return Json("erro");
            }
            else
            {
                Imagem img = db.Imagem.Find(id);
                Funcoes.ExcluirArquivo(Request.PhysicalApplicationPath + "Imagens\\" + img.Img_nome);
                db.Imagem.Remove(img);
                db.SaveChanges();
                return Json("ok");
            }
 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddImagens(Imagem img,HttpPostedFileBase arquivo)
        {
            string nomearq, valor;
            var lista = db.Imagem.ToList();

            if (arquivo != null)
            {
                Funcoes.CriarDiretorio();

                nomearq = DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(arquivo.FileName);
                valor = Funcoes.UploadArquivoImagensRef(arquivo, nomearq);
                if (valor == "sucesso")
                {       
                    img.Img_nome = nomearq;

                    db.Imagem.Add(img);
                    db.SaveChanges();
                    TempData["Msg"] = "Imagem Inserida";
                    lista = db.Imagem.ToList();
                    return View("ExibirImagens", lista);

                }
                else if(valor == "Tamanho Máximo permitido é de  2000  kb!") {
                    TempData["Msg"] = "Imagem muito grande";
                    return View("ExibirImagens", lista); 
                }
                else if (valor == "Extensão inválida, só são permitidas .png e .jpg!")
                {
                    TempData["Msg"] = "Formato de arquivo Invalido !";
                    return View("ExibirImagens", lista);
                }
                else
                {
                    TempData["Msg"] = "Erro !";
                    return View("ExibirImagens", lista);
                }
            }
            else {
                TempData["Msg"] = "Insira a Imagem";
                return View("ExibirImagens", lista); 
            }
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

Gesture_Go_v1/Controllers/PaginaInicialController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Gesture_Go_v1.Models;

namespace Gesture_Go_v1.Controllers
{
    public class PaginaInicialController : Controller
    {
        private Contexto db = new Contexto();

        public ActionResult Index()
        {
            return View("PaginaInicialIndex");
        }


        [Authorize]
        public ActionResult PaginaInicialIndex()
        {
            int id = Convert.ToInt32(User.Identity.Name.Split('|')[0]);


            var diaAtual = DateTime.Now;
            var hojeSemana = DateTime.Now.AddDays(((double)DateTime.Now.DayOfWeek) * -1);
            var listaTeste = db.HistoricoPratica.Where(x => x.data.Day == diaAtual.Day && x.data.Month == diaAtual.Month && x.data.Year == diaAtual.Year && x.UsuarioId == id).ToList().Select(g => new { g.tempoPratica, g.qtdImagens }).ToList();
            var ListaSemana = db.HistoricoPratica.Where(x => x.data.Day >= hojeSemana.Day && x.data.Month >= hojeSemana.Month && x.data.Year >= hojeSemana.Year && x.UsuarioId == id).Select(g => new { g.tempoPratica, g.qtdImagens }).ToList();
            int a = 0;
            int b = 0;

            foreach (var item in listaTeste)
            {
                a += Funcoes.ConverteSegudos(item.tempoPratica) * item.qtdImagens;
            }

            foreach (var item in ListaSemana)
            {
                b += Funcoes.ConverteSegudos(item.tempoPratica) * item.qtdImagens;
            }

            TimeSpan time = TimeSpan.FromSeconds(a);
            TimeSpan timeS = TimeSpan.FromSeconds(b);

            ViewBag.a = Convert.ToInt32(((double)a / 3600) * 100);
            ViewBag.b = Convert.ToInt32(((double)b / (3600 * 7)) * 100); ;

            if (a >= 3600) { ViewBag.horaCompleto = "Completo"; }
            if (b >= (3600 * 7)) { ViewBag.semanaCompleto = "Completo"; }

            ViewBag.hora = time.ToString(@"h\:mm\:ss");
            ViewBag.semana = timeS.ToString(@"h\:mm\:ss");
            return View();
        }

        [Authorize]
        public ActionResult Teste(VMSessao ses)
        {
            ViewBag.segundos = Funcoes.ConverteSegudos(ses.ses_timer);
            ViewBag.timer = ses.ses_timer;
            var lista = Funcoes.Randomize(db.Imagem.Where(x => x.Img_tipo == ses.ses_tipo).ToList());
            return View(lista);
        }

        [Authorize]
        public ActionResult Pratica(VMSessao ses)
        {
            if (TempData["Postado"] != null)
            {
                ViewBag.toast = true;
            }

            ViewBag.timer = ses.ses_timer;
            ViewBag.segundos = Funcoes.ConverteSegudos(ses.ses_timer);
            var lista = Funcoes.Randomize(db.Imagem.Where(x => x.Img_tipo == ses.ses_tipo).ToList());
            return View(lista);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PaginaInicialIndex(VMSessao ses)
        {
            return RedirectToAction("Pratica", ses);
        }



        public ActionResult Sair()
        {
            Session["id"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult EditarPerfil()
        {
            int id = Convert.ToInt32(User.Identity.Name.Split('|')[0]);
            Usuario usu = new Usuario();
            usu = db.Usuario.Find(id);
            return View(usu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarPerfil(Usuario usu, HttpPostedFileBase arquivo)
        {
            Usuario usuario = db.Usuario.Find(usu.Id);
            if (ModelState.IsValid)
            {
                usuario.Nome = usu.Nome;
                
                if (arquivo != null)
                {
                    
                    string nomearq, valor;

                    nomearq = DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(arquivo.FileName);
                    valor = Funcoes.UploadArquivoImagensPerfil(arquivo, nomearq);
                    if (valor == "sucesso")
                    {
                        Funcoes.ExcluirArquivo(Request.PhysicalApplicationPath + "ImgUsuarios\\" + usu.ImgPerfil);
                        usuario.ImgPerfil = nomearq;
                    }
                }
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, usuario.Id + "|" + usuario.Email + "|" + usuario.Nome + "|" + usuario.PerfilId + "|" + usuario.ImgPerfil, DateTime.Now, DateTime.Now.AddMinutes(30), false, usuario.PerfilId.ToString());
                string hash = FormsAuthentication.Encrypt(ticket);
                HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, hash);
                Response.Cookies.Add(cookie);
                TempData["Msg"] = "Atalizado com sucesso!";
                return RedirectToAction("Index");
            }
            TempData["Msg"]="Erro: Campo inválido";
            return View(usu);
        }
    }
}

Gesture_Go_v1/Controllers/PostController.cs
using Gesture_Go_v1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Gesture_Go_v1.Controllers
{
    public class PostController : Controller
    {
        private Contexto db = new Contexto();

        [Authorize]
        public ActionResult Posts()
        {
            var posts = db.Posts.Where(x => x.Pos_Status).OrderByDescending(x => x.data).ToList();
            return View(posts);
        }


        [Authorize]
        public ActionResult MeusPosts()
        {
            int id = Convert.ToInt32(User.Identity.Name.Split('|')[0]);
            var posts = db.Posts.Where(x => x.UsuarioId == id).ToList();
            return View(posts);
        }

        [Authorize]
        public ActionResult Comentarios(int id)
        {

            var comentarios = db.Comentarios.Where(x => x.PostsPos_id == id).ToList();
            return View(comentarios);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CriarCometario(Comentarios com)
        {
           com.UsuarioId = Convert.ToInt32(User.Identity.Name.Split('|')[0]);

            return View();
        }

        [Authorize]
        public ActionResult CriarPost(int? imgRef)
        {
            TempData["imgRefe"] = imgRef;
            return PartialView();
        }


        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public JsonResult CriarPost(string id, string titulo, HttpPostedFileBase imagem)
        {
            if(titulo.Length <= 10)
            {
                return Json("tpequeno");
            }

            Posts posts = new Posts();

            string nomearq, valor;
            
                if (imagem != null)
                {
                    Funcoes.CriarDiretorio();
                   
                    nomearq = DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(imagem.FileName);
                    valor = Funcoes.UploadArquivo(imagem, nomearq);
                    if (valor == "sucesso")
                    {
                        posts.Pos_Titulo = titulo;
                        posts.ImagemId = Convert.ToInt32(id);
                        posts.UsuarioId = Convert.ToInt32(User.Identity.Name.Split('|')[0]);
                        posts.data = DateTime.Now;
                        posts.Pos_imgUpload = nomearq;
                        posts.Pos_Status = true;

                        db.Posts.Add(posts);
                        db.SaveChanges();
                        ViewBag.toast = "post criado com sucesso";
                        return Json("ok");

                    } else { return Json("imgGrande"); }

                } else { return Json("semImg"); }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public JsonResult HistoticoPratica(int qtdPratica, DateTime timer)
        {

            HistoricoPratica hist = new HistoricoPratica();
            hist.UsuarioId = Convert.ToInt32(User.Identity.Name.Split('|')[0]);
            hist.data = DateTime.Now;
            hist.qtdImagens = qtdPratica;
            hist.tempoPratica = timer;
            db.HistoricoPratica.Add(hist);
            db.SaveChanges();

            return Json("");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public JsonResult Comentar(string comentario, int post)
        {

            Comentarios com = new Comentarios();
            com.PostsPos_id = post;
            com.UsuarioId = Convert.ToInt32(User.Identity.Name.Split('|')[0]);
            com.Data = DateTime.Now;
            com.Comentario = comentario;
            db.Comentarios.Add(com);
            db.SaveChanges();

            return Json("ok");
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

Gesture_Go_v1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestrure Go</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script defer src="https://cdn.tiny.cloud/1/no-apikey/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script defer src="https://cdn.tiny.cloud/1/no-origin/tinymce/5.10.0-121/tinymce.min.js"></script>
</head>
<body>


    @if (User.Identity.IsAuthenticated)
    {
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("Gesture Go", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>

        <div class="collapse navbar-collapse ml-3" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item ">
                    @Html.ActionLink(" Home", "PaginaInicialIndex", "PaginaInicial", new { area = "" }, new { @class = "nav-link bi bi-house-fill" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink(" Posts", "Posts", "Post", new { area = "" }, new { @class = "nav-link bi bi-file-post-fill" })
                </li>
            </ul>
        </div>


        <div class="dropdown mr-4">
            <img  class="rounded-circle" style="width: 30px;" src="~/ImgUsuarios/@{if (User.Identity.Name.Split('|')[4] != "") {@User.Identity.Name.Split('|')[4]} else {<text>user.png</text>} }?@DateTime.Now.ToString("yyyyMMddHHmmss")"/>
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                @{ <span class=" text-white h6 font-weight-light">@User.Identity.Name.Split('|')[1]</span>}
            </button>
            <div class="dropdown-menu bg-secondary" style="width: 200px;" aria-labelledby="dropdownMenuButton">
                @Html.ActionLink(" Edit. Perfil", "EditarPerfil", "PaginaInicial", new { area = "" }, new { @class = "bi bi-file-person nav-link text-white " })
                @{
                    string a = Convert.ToString(User.Identity.Name.Split('|')[3]);

                    if (a == "1")
                    {
                        <li class="nav-item">
                            @Html.ActionLink(" Adm. imagens", "AddImagens", "AdmImagens", new { area = "" }, new { @class = "text-white nav-link bi bi-pencil-square" })
                        </li>
                    }
                }
                <button class="btn btn-outline-secondary">
                    @Html.ActionLink(" Sair", "Sair", "Home", new { @class = "text-white bi bi-arrow-bar-left" })
                </button>
            </div>
        </div>
    </nav>
    }

<div class="container body-content pt-2">
    @RenderBody()

    <footer>
    </footer>
    <div class="toast" id="msg" style="position: fixed; top: 40px; right: 10px;" data-delay="4000">
        <div class="toast-header">
            <strong class="mr-auto bi bi-chat-dots"> Mensagem</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body texto h6">
            @TempData["Msg"]
        </div>
    </div>
</div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

<script>

    @if (TempData["Msg"] != null) {
        <text>$('#msg').toast('show');</text>
    }
</script>
</body>
</html>